import NextImage from 'next/image';

import roi from './project-roi.png';

import classes from './ROI.module.css';

import Container from 'src/components/atoms/Container';

import Typography from 'src/components/atoms/Typography';

export default function ROIFrame() {
    return (
        <div className={classes.wrapper}>
            <div className={classes.radial_bg} />
            <Container>
                <div className="grid lg:grid-cols-2 lg:gap-10">
                    <div className="flex flex-col space-y-[24px] lg:space-y-[40px]">
                        <Typography variant="h2" className="lg:text-start">
                            PROJECT ROI
                        </Typography>

                        <div className="flex items-center justify-center lg:hidden">
                            <NextImage src={roi} alt="project roi" className="" width={300} height={0} />
                        </div>

                        <Typography variant="body1" className="lg:text-start">
                            The Shift DAO MySeven token (SDMS) value is designed to represent the value of the
                            underlying acquired equity derivative instruments.
                            <br /> <br />
                            At the current valuation of 50 million USD, we at Shift DAO expect an upside potential of
                            ~10x on the investment based on our valuation targets set based on similar industry players.
                            <br /> <br />
                            The biggest player on the market has reached an impressive valuation of 13 billion USD
                            during 2022 with only 1 million active users. With strong influencer partnerships and an
                            extensive roll-out plan MySeven Platform aims to gain a considerably larger user base within
                            the first years of operations!
                            <br /> <br />
                            To ensure sustainable value creation, the company valuation is tied to the real economic
                            revenue generated by the masses in the ecosystem through user interactions, advertisement,
                            and in-app purchases.
                        </Typography>
                    </div>

                    <div className="hidden items-center justify-center lg:flex">
                        <NextImage src={roi} alt="project roi" className="" width={460} height={0} />
                    </div>
                </div>
                <div className="my-[80px] h-[1px] bg-light/20 lg:my-[120px]" />
            </Container>
        </div>
    );
}
